#!/bin/sh

BASE="$HOME/dotfiles/bspwm"
export PYTHONWARNINGS=ignore::SyntaxWarning

# monitor layout
if [ -x "$BASE/display-apply.sh" ]; then
  sh "$BASE/display-apply.sh"
else
  printf "No display script found at %s/display-apply.sh\n" "$BASE"
fi

# Keyboard Remapping
setxkbmap -layout dk -option &
sleep 1 && xmodmap "$HOME/dotfiles/mods/.Xmodmap" &

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-2   -d 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 1

# bspwm styles 
if [ -x "$BASE/styling-apply.sh" ]; then
  sh "$BASE/styling-apply.sh"
else
  printf "No style script found at %s/styling-apply.sh\n" "$BASE"
fi

# startup applications
if [ -x "$BASE/start-apps.sh" ]; then
  sh "$BASE/start-apps.sh"
else
  printf "No startup script found at %s/start-apps.sh\n" "$BASE"
fi

