#!/bin/sh

BASE="$HOME/dotfiles/bspwm/scripts"
BASE_LOCAL="$HOME/dotfiles/bspwm/local"
export PYTHONWARNINGS=ignore::SyntaxWarning

# monitor layout
if [ -x "$BASE/display-apply.sh" ]; then
  sh "$BASE/display-apply.sh"
else
  printf "No display script found at %s/display-apply.sh\n" "$BASE"
fi

# Keyboard Remapping
setxkbmap -layout dk -option &
sleep 1 && xmodmap "$HOME/dotfiles/mods/.Xmodmap" &

pgrep -x sxhkd >/dev/null || sxhkd &


if [ -x "$BASE/workspaces-apply.sh" ]; then
  sh "$BASE/workspaces-apply.sh"
else
printf "No workspace script found at %s/workspaces-apply.sh\n" "$BASE"
fi

# bspwm styles 
if [ -x "$BASE/styling-apply.sh" ]; then
  sh "$BASE/styling-apply.sh"
else
  printf "No style script found at %s/styling-apply.sh\n" "$BASE"
fi

# startup applications
if [ -x "$BASE/start-apps.sh" ]; then
  sh "$BASE/start-apps.sh"
else
  printf "No startup script found at %s/start-apps.sh\n" "$BASE"
fi

# local
if [ -x "$BASE_LOCAL/local-apply.sh" ]; then
  sh "$BASE_LOCAL/local-apply.sh"
else
    printf "No startup script found at %s/local-apply.sh\n" "$BASE_LOCAL"
fi

 
