
# Uncomment to enable zsh profiling
# zmodload zsh/zprof

# autocomplete
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

autoload -Uz compinit
compinit -C

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#56B6C2'

bindkey '^I' autosuggest-accept
bindkey '^F' complete-word

# theme (oh my posh)
export PATH=$PATH:$HOME/.local/bin
eval "$(oh-my-posh init zsh --config ~/dotfiles/omp/material.omp.json)"


# utilities
eval "$(zoxide init zsh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"


#commands
alias zhd='nano ~/.zshrc'
alias zhr='source ~/.zshrc'
alias zhc='code ~/.zshrc'
alias ls='ls --color=auto'


# fnm
FNM_PATH="/home/kristian/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi

# Uncomment to enable profiling
# zprof
